version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3310:3306"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=reponsitory_db
      - MYSQL_ROOT_PASSWORD=secret
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --max_allowed_packet=134217728'
    networks:
      - app-network-reponsitory

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - MAX_EXECUTION_TIME=1200
      - MEMORY_LIMIT=1512M
      - UPLOAD_LIMIT=258M
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network-reponsitory

volumes:
  dbdata:

networks:
  app-network-reponsitory:
    driver: bridge